"""
tests.test_validation
Tests for Parquet metadata validation logic.
"""

import pytest
import polars as pl
from pathlib import Path
from sweetbits.metadata import validate_sweetbits_parquet, write_parquet_with_metadata, get_standard_metadata
from sweetbits.tables import generate_table_logic

def test_validate_non_sweetbits_parquet(tmp_path):
    """Tests that a standard Parquet file (no metadata) fails validation."""
    pfile = tmp_path / "plain.parquet"
    df = pl.DataFrame({"sample_id": ["S1"], "t_id": [1], "clade_reads": [10], "taxon_reads": [10]})
    df.write_parquet(pfile)
    
    with pytest.raises(ValueError, match="not generated by SweetBITS"):
        validate_sweetbits_parquet(pfile, expected_type="REPORT_PARQUET")

def test_validate_wrong_type(tmp_path):
    """Tests that a SweetBITS file with the wrong type fails validation."""
    pfile = tmp_path / "wrong_type.parquet"
    df = pl.DataFrame({"sample_id": ["S1"], "t_id": [1], "clade_reads": [10], "taxon_reads": [10]})
    meta = get_standard_metadata(file_type="KRAKEN_PARQUET")
    write_parquet_with_metadata(df, pfile, meta)
    
    with pytest.raises(ValueError, match="File type mismatch"):
        validate_sweetbits_parquet(pfile, expected_type="REPORT_PARQUET")

def test_validate_missing_columns(tmp_path):
    """Tests that a SweetBITS file missing required columns fails validation."""
    pfile = tmp_path / "missing_cols.parquet"
    # Missing 'taxon_reads'
    df = pl.DataFrame({"sample_id": ["S1"], "t_id": [1], "clade_reads": [10]})
    meta = get_standard_metadata(file_type="REPORT_PARQUET")
    write_parquet_with_metadata(df, pfile, meta)
    
    with pytest.raises(ValueError, match="missing required columns: taxon_reads"):
        validate_sweetbits_parquet(pfile, expected_type="REPORT_PARQUET", required_columns=["sample_id", "taxon_reads"])

def test_table_validation_integration(tmp_path):
    """Tests that generate_table_logic raises a clear error on invalid input."""
    pfile = tmp_path / "invalid.parquet"
    df = pl.DataFrame({"a": [1]})
    df.write_parquet(pfile)
    
    output_csv = tmp_path / "out.csv"
    
    # generate_table_logic should catch this via validate_sweetbits_parquet
    with pytest.raises(ValueError, match="not generated by SweetBITS"):
        generate_table_logic(pfile, output_csv)
