"""
sweetbits.metadata
Utilities for reading and writing Arrow-level metadata in Parquet files.
"""

import pyarrow.parquet as pq
import pyarrow as pa
from pathlib import Path
from datetime import datetime
import sys
from typing import Dict, Any, Optional, List, Tuple
from sweetbits import __version__

MINIMUM_COMPATIBLE_VERSION = "0.1.0"

def _parse_version(v_str: str) -> Tuple[int, ...]:
    """Parses a semantic version string into a tuple of integers."""
    parts = v_str.split('-')[0].split('.')
    return tuple(int(p) if p.isdigit() else 0 for p in parts)

def get_standard_metadata(
    file_type: str, 
    source_path: Optional[Path] = None,
    compression: str = "None",
    sorting: str = "None",
    data_standard: str = "GENERIC",
    report_format: str = "HYPERLOGLOG"
) -> Dict[str, str]:
    """
    Generates the standard metadata dictionary for SweetBITS parquet files.

    Args:
        file_type     : String identifier for the file schema (e.g., 'REPORT_PARQUET').
        source_path   : Absolute path to the original source of the data.
        compression   : Description of the compression used.
        sorting       : Description of the column sorting applied.
        data_standard : The detected standard profile ('SWEBITS' or 'GENERIC').
        report_format : The detected input format ('HYPERLOGLOG' or 'LEGACY').

    Returns:
        A dictionary of metadata strings ready for Arrow schema injection.
    """
    args = sys.argv[1:]
    command_str = " ".join(args)
    
    # Identify the invocation command
    if not sys.argv[0].endswith("sweetbits"):
        invocation = f"python {sys.argv[0]} {command_str}".strip()
    else:
        invocation = f"sweetbits {command_str}".strip()

    metadata = {
        "sweetbits_version": __version__,
        "file_type": file_type,
        "execution_command": invocation,
        "creation_time": datetime.now().isoformat(),
        "compression": compression,
        "sorting": sorting,
        "source_path_abs": str(source_path.resolve()) if source_path else "Unknown",
        "data_standard": data_standard,
        "report_format": report_format
    }
    return metadata

def write_parquet_with_metadata(df: 'pl.DataFrame', output_path: Path, metadata: Dict[str, str], **kwargs):
    """
    Writes a Polars DataFrame to Parquet with custom file-level metadata.

    Args:
        df          : The Polars DataFrame to save.
        output_path : Target path for the Parquet file.
        metadata    : Dictionary of metadata to inject into the Arrow schema.
        **kwargs    : Additional arguments passed to pyarrow.parquet.write_table.
    """
    table = df.to_arrow()
    existing_meta = table.schema.metadata or {}
    merged_meta = {**existing_meta}
    for k, v in metadata.items():
        merged_meta[k.encode()] = str(v).encode()
        
    new_schema = table.schema.with_metadata(merged_meta)
    table = table.cast(new_schema)
    pq.write_table(table, output_path, **kwargs)

def read_parquet_metadata(file_path: Path) -> Dict[str, str]:
    """
    Reads the custom metadata from a Parquet file header.

    Args:
        file_path : Path to the Parquet file.

    Returns:
        A dictionary of decoded metadata strings.
    """
    schema = pq.read_schema(file_path)
    if not schema.metadata:
        return {}
    return {k.decode(): v.decode() for k, v in schema.metadata.items()}

def validate_sweetbits_parquet(
    file_path: Path, 
    expected_type: str,
    required_columns: Optional[List[str]] = None
) -> Dict[str, str]:
    """
    Validates that a Parquet file was generated by SweetBITS and matches the expected type.

    Args:
        file_path        : Path to the Parquet file to validate.
        expected_type    : The 'file_type' expected in the metadata (e.g. 'REPORT_PARQUET').
        required_columns : Optional list of column names that must be present in the schema.

    Returns:
        The decoded metadata dictionary if validation passes.

    Raises:
        ValueError       : If the file is not a valid SweetBITS Parquet or has incorrect type/columns.
    """
    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {file_path}")

    # Read schema once to check both metadata and columns
    schema = pq.read_schema(file_path)
    metadata = {k.decode(): v.decode() for k, v in (schema.metadata or {}).items()}

    # 1. Check if generated by SweetBITS
    if "sweetbits_version" not in metadata:
        raise ValueError(
            f"The file '{file_path.name}' was not generated by SweetBITS. "
            "Missing 'sweetbits_version' in metadata."
        )
        
    # 2. Check Version Compatibility
    file_version = metadata["sweetbits_version"]
    file_v_tuple = _parse_version(file_version)
    mcv_tuple = _parse_version(MINIMUM_COMPATIBLE_VERSION)
    current_v_tuple = _parse_version(__version__)

    if file_v_tuple < mcv_tuple:
        raise ValueError(
            f"The file '{file_path.name}' was generated by SweetBITS v{file_version}, "
            f"which is older than the minimum compatible version v{MINIMUM_COMPATIBLE_VERSION}. "
            "Please re-process your data with the current version."
        )

    if file_v_tuple > current_v_tuple:
        raise ValueError(
            f"The file '{file_path.name}' was generated by a newer version of SweetBITS (v{file_version}). "
            f"You are currently using v{__version__}. Please upgrade SweetBITS to process this file."
        )

    # 3. Check File Type
    actual_type = metadata.get("file_type", "Unknown")
    if actual_type != expected_type:
        raise ValueError(
            f"File type mismatch for '{file_path.name}'. "
            f"Expected '{expected_type}', but found '{actual_type}'."
        )

    # 4. Check Required Columns
    if required_columns:
        actual_columns = schema.names
        missing = [c for c in required_columns if c not in actual_columns]
        if missing:
            raise ValueError(
                f"The file '{file_path.name}' is missing required columns: {', '.join(missing)}. "
                "This file may have been tampered with or generated by an incompatible version."
            )

    return metadata
