"""
sweetbits.metadata
Utilities for reading and writing JSON companion metadata files.
"""

import json
import polars as pl
from pathlib import Path
from datetime import datetime
import sys
from typing import Dict, Any, Optional, List, Tuple
from sweetbits import __version__

MINIMUM_COMPATIBLE_VERSION = "0.1.0"

def _parse_version(v_str: str) -> Tuple[int, ...]:
    """Parses a semantic version string into a tuple of integers."""
    parts = v_str.split('-')[0].split('.')
    return tuple(int(p) if p.isdigit() else 0 for p in parts)

def get_standard_metadata(
    file_type: str, 
    source_path: Optional[Path] = None,
    compression: str = "None",
    sorting: str = "None",
    data_standard: str = "GENERIC",
    report_format: str = "HYPERLOGLOG"
) -> Dict[str, str]:
    """
    Generates the standard metadata dictionary for SweetBITS outputs.

    Args:
        file_type     : String identifier for the file schema (e.g., 'REPORT_PARQUET').
        source_path   : Absolute path to the original source of the data.
        compression   : Description of the compression used.
        sorting       : Description of the column sorting applied.
        data_standard : The detected standard profile ('SWEBITS' or 'GENERIC').
        report_format : The detected input format ('HYPERLOGLOG' or 'LEGACY').

    Returns:
        A dictionary of metadata strings.
    """
    args = sys.argv[1:]
    command_str = " ".join(args)
    
    # Identify the invocation command
    if not sys.argv[0].endswith("sweetbits"):
        invocation = f"python {sys.argv[0]} {command_str}".strip()
    else:
        invocation = f"sweetbits {command_str}".strip()

    metadata = {
        "sweetbits_version": __version__,
        "file_type": file_type,
        "execution_command": invocation,
        "creation_time": datetime.now().isoformat(),
        "compression": compression,
        "sorting": sorting,
        "source_path_abs": str(source_path.resolve()) if source_path else "Unknown",
        "data_standard": data_standard,
        "report_format": report_format
    }
    return metadata

def save_companion_metadata(output_file: Path, metadata: Dict[str, str]):
    """
    Saves a JSON companion file next to the output file containing its provenance metadata.

    Args:
        output_file : The path to the main data file (e.g., 'table.parquet').
        metadata    : The metadata dictionary to save.
    """
    companion_file = output_file.with_name(f"{output_file.name}.json")
    with open(companion_file, "w") as f:
        json.dump(metadata, f, indent=4)

def read_companion_metadata(file_path: Path) -> Dict[str, str]:
    """
    Reads the custom metadata from a JSON companion file.

    Args:
        file_path : Path to the main data file.

    Returns:
        A dictionary of metadata strings, or an empty dict if the file is missing.
    """
    companion_file = file_path.with_name(f"{file_path.name}.json")
    if not companion_file.exists():
        return {}
    with open(companion_file, "r") as f:
        return json.load(f)

def validate_sweetbits_file(
    file_path: Path, 
    expected_type: str,
    required_columns: Optional[List[str]] = None
) -> Dict[str, str]:
    """
    Validates that a file was generated by SweetBITS using its JSON companion file.

    Args:
        file_path        : Path to the data file to validate.
        expected_type    : The 'file_type' expected in the metadata (e.g. 'REPORT_PARQUET').
        required_columns : Optional list of column names that must be present in the schema.

    Returns:
        The decoded metadata dictionary if validation passes.

    Raises:
        FileNotFoundError: If the data file or its companion JSON file is missing.
        ValueError       : If the file is not a valid SweetBITS file or has incorrect type/columns.
    """
    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {file_path}")

    companion_file = file_path.with_name(f"{file_path.name}.json")
    if not companion_file.exists():
        raise FileNotFoundError(
            f"Missing companion metadata file: {companion_file.name}. "
            "SweetBITS requires this JSON file to verify data integrity and provenance."
        )

    with open(companion_file, "r") as f:
        try:
            metadata = json.load(f)
        except json.JSONDecodeError:
            raise ValueError(f"Companion metadata file '{companion_file.name}' is corrupted or invalid JSON.")

    # 1. Check if generated by SweetBITS
    if "sweetbits_version" not in metadata:
        raise ValueError(
            f"The file '{file_path.name}' (via its companion JSON) lacks provenance. "
            "Missing 'sweetbits_version' in metadata."
        )
        
    # 2. Check Version Compatibility
    file_version = metadata["sweetbits_version"]
    file_v_tuple = _parse_version(file_version)
    mcv_tuple = _parse_version(MINIMUM_COMPATIBLE_VERSION)
    current_v_tuple = _parse_version(__version__)

    if file_v_tuple < mcv_tuple:
        raise ValueError(
            f"The file '{file_path.name}' was generated by SweetBITS v{file_version}, "
            f"which is older than the minimum compatible version v{MINIMUM_COMPATIBLE_VERSION}. "
            "Please re-process your data with the current version."
        )

    if file_v_tuple > current_v_tuple:
        raise ValueError(
            f"The file '{file_path.name}' was generated by a newer version of SweetBITS (v{file_version}). "
            f"You are currently using v{__version__}. Please upgrade SweetBITS to process this file."
        )

    # 3. Check File Type
    actual_type = metadata.get("file_type", "Unknown")
    if actual_type != expected_type:
        raise ValueError(
            f"File type mismatch for '{file_path.name}'. "
            f"Expected '{expected_type}', but found '{actual_type}'."
        )

    # 4. Check Required Columns
    if required_columns:
        ext = file_path.suffix.lower()
        if ext == ".parquet":
            schema = pl.scan_parquet(file_path).collect_schema()
        elif ext in [".csv", ".tsv"]:
            # Lazily peek at the CSV header
            separator = "\t" if ext == ".tsv" else ","
            schema = pl.scan_csv(file_path, separator=separator).collect_schema()
        else:
            raise ValueError(f"Cannot validate columns for unknown file type: {ext}")
            
        actual_columns = list(schema.keys())
        missing = [c for c in required_columns if c not in actual_columns]
        if missing:
            raise ValueError(
                f"The file '{file_path.name}' is missing required columns: {', '.join(missing)}. "
                "This file may have been tampered with or generated by an incompatible version."
            )

    return metadata
